name: Release

env:
  PLUGIN_NAME: logseq-plugin-wrap-plu

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Package
        run: |
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json icon.png ${{ env.PLUGIN_NAME }}
          mv dist ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.PLUGIN_NAME }}.zip
